const Users = [
  {
    userId: 1,
    userFirstName: "Pradeep",
    userLastName: "Joshi",
    roles: ["admin", "user"],
    previousOrders: [
      {
        billDate: "01/01/2023",
        billAmount: "Rs. 254.00",
        listItems: [{ item: {}, orderedQuantity: 2 }],
      },
    ],
    customItems: [
      {
        itemId: 101,
        itemName: "Nice Time",
        img: "",
        isBaseItem: true,
        catigory: "Snacks",
        defaultQuantity: 1,
        defaultUnitQuantity: "pc",
        price: 150.0,
      },
      {
        itemId: 102,
        itemName: "Britania Rusk",
        img: "",
        isBaseItem: true,
        catigory: "Snacks",
        defaultQuantity: 1,
        defaultUnitQuantity: "pc",
        price: 150.0,
      },
    ],
  },
];

const BaseItemList = [
  {
    itemId: 1,
    itemName: "Mong Daal",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 100,
  },
  {
    itemId: 2,
    itemName: "Channa Daal",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 90.0,
  },
  {
    itemId: 3,
    itemName: "Sugar",
    img: "",
    isBaseItem: true,
    catigory: "Daily Esentials",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 110.0,
  },
  {
    itemId: 4,
    itemName: "Tooth Paste",
    img: "",
    isBaseItem: true,
    catigory: "Daily Esentials",
    defaultQuantity: 1,
    defaultUnitQuantity: "pc",
    price: 150.0,
  },
  {
    itemId: 5,
    itemName: "Nivya Cream",
    img: "",
    isBaseItem: true,
    catigory: "Cosmatic",
    defaultQuantity: 1,
    defaultUnitQuantity: "pc",
    price: 150.0,
  },
  {
    itemId: 6,
    itemName: "Rajma",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 100,
  },
  {
    itemId: 7,
    itemName: "Kala Daal",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 90.0,
  },
  {
    itemId: 8,
    itemName: "Arhar Daal",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 100,
  },
  {
    itemId: 9,
    itemName: "Mong Daal",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 90.0,
  },
  {
    itemId: 10,
    itemName: "Mix Daal",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 100,
  },
  {
    itemId: 11,
    itemName: "Safed Chola",
    img: "",
    isBaseItem: true,
    catigory: "Grains",
    defaultQuantity: 500,
    defaultUnitQuantity: "grms",
    price: 90.0,
  },
  
];

export const CNTX_USER = Users[0];
export const FINAL_DATA_LIST = BaseItemList.concat(CNTX_USER.customItems);
